emu:
  image: birdhouse/emu
  ports:
    - "9001:9001"
    - "8081:8081"
    - "8443:8443"
    - "8080:8080"
  environment:
    HOSTNAME: localhost
    HTTP_PORT: 8080
    HTTPS_PORT: 8443
    OUTPUT_PORT: 8081
#  volumes:
#    - /tmp/data:/opt/birdhouse/var/lib
#    - /tmp/log:/opt/birdhouse/var/log
#  volume_driver: local
