name: emu
channels: 
  - birdhouse
  - defaults
dependencies:
- alabaster=0.7.8=py27_0
- babel=2.3.3=py27_0
- backports=1.0=py27_0
- eventlet=0.16.1=py27_0
- htmltmpl=1.22=py27_1
- nginx=1.8.0=0
- python-magic=0.4.6=py27_1
- pywps=3.2.5=py27_4
- cffi=1.6.0=py27_0
- cryptography=1.4=py27_0
- curl=7.49.0=0
- decorator=4.0.10=py27_0
- docutils=0.12=py27_2
- enum34=1.1.6=py27_0
- execnet=1.2.0=py27_0
- gdal=1.11.0=np19py27_0
- get_terminal_size=1.0.0=py27_0
- gevent=1.1.1=py27_0
- greenlet=0.4.10=py27_0
- gunicorn=19.1.0=py27_0
- idna=2.0=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.14=py27_0
- ipython=4.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_1
- libffi=3.2.1=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.6.0=py27_0
- mako=1.0.4=py27_0
- markupsafe=0.23=py27_2
- meld3=1.0.2=py27_0
- mkl=11.3.3=0
- numpy=1.9.3=py27_3
- openssl=1.0.2h=1
- pastedeploy=1.5.2=py27_1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pcre=8.31=0
- pep8=1.7.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.2=py27_0
- pip=8.1.2=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.4.31=py27_0
- pyasn1=0.1.9=py27_0
- pycparser=2.14=py27_1
- pygments=2.1.3=py27_0
- pyopenssl=0.16.0=py27_0
- pytest=2.9.2=py27_0
- pytest-cache=1.0=py27_0
- pytest-pep8=1.0.6=py27_0
- python=2.7.12=0
- pytz=2016.4=py27_0
- pyyaml=3.11=py27_4
- readline=6.2=2
- setuptools=23.0.0=py27_0
- simplegeneric=0.8.1=py27_1
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.4.1=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- sqlite=3.13.0=0
- supervisor=3.1.3=py27_1
- tk=8.5.18=0
- traitlets=4.2.1=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - genshi==0.7
